import en from "./en.json";
import hi from "./hi.json";
import mr from "./mr.json";
import ta from "./ta.json";
import te from "./te.json";
import bn from "./bn.json";
import gu from "./gu.json";
import kn from "./kn.json";
import ml from "./ml.json";
import pa from "./pa.json";
import assamese from "./as.json";
import odia from "./or.json";

export const languages = [
  ["en", "English"], ["hi", "हिन्दी"], ["mr", "मराठी"], ["ta", "தமிழ்"],
  ["te", "తెలుగు"], ["bn", "বাংলা"], ["gu", "ગુજરાતી"], ["kn", "ಕನ್ನಡ"],
  ["ml", "മലയാളം"], ["pa", "ਪੰਜਾਬੀ"], ["as", "অসমীয়া"], ["or", "ଓଡ଼ିଆ"],
];
export const speechLocales = { en:"en-IN", hi:"hi-IN", mr:"mr-IN", ta:"ta-IN", te:"te-IN", bn:"bn-IN", gu:"gu-IN", kn:"kn-IN", ml:"ml-IN", pa:"pa-IN", as:"as-IN", or:"or-IN" };
const catalogs = { en, hi, mr, ta, te, bn, gu, kn, ml, pa, as: assamese, or: odia };

// Keys added after the initial prototype.  Keeping them here makes every
// locale complete immediately; locale files override these defaults as they
// are translated.  This also prevents a raw key from ever leaking into UI.
const defaults = {
  enterFullName: "Enter your full name", phonePlaceholder: "10-digit mobile number", emailPlaceholder: "you@example.com", usernamePlaceholder: "Choose a username", passwordPlaceholder: "At least 6 characters", confirmPasswordPlaceholder: "Re-enter your password", loggingIn: "Logging in…", registering: "Registering…", loginSubtitle: "Login to access PMFBY Crop Damage Detection", registerSubtitle: "Register to start analyzing crop damage", noAccount: "Don't have an account?", hasAccount: "Already have an account?", pmfbyProject: "PMFBY Project", aiRemoteSensing: "AI & Remote Sensing Based", profileSubtitle: "Your PMFBY account details", profileLoginRequired: "Please login to view your profile.", studySubtitle: "Choose a state, district, and analysis periods.",
  claimSubtitle: "Submit crop-loss details for verification.", evidenceForHumanReview: "Evidence for human review", evidenceDescription: "These details enable field-level verification.", claimEventType: "Claim event type", cropStage: "Crop stage", claimDate: "Claim date", sowingDate: "Sowing date", selectEvent: "Select event", selectCropStage: "Select crop stage", eventFlood: "Flood", eventDrought: "Drought", eventCyclone: "Cyclone / storm", eventPestDisease: "Pest / disease", eventHailRain: "Hail / unseasonal rain", other: "Other", stageGermination: "Germination", stageVegetative: "Vegetative", stageFlowering: "Flowering", stageHarvest: "Harvest", exampleCrop: "Example: Grape, Apple, Tomato", exampleLoss: "Example: 40", exampleArea: "Example: 2.5", villagePlaceholder: "Enter village or farm location", farmLatitude: "Farm latitude", farmLongitude: "Farm longitude", farmPolygon: "Farm boundary (optional)", latitudePlaceholder: "Example: 20.5937", longitudePlaceholder: "Example: 78.9629", polygonPlaceholder: "Optional GeoJSON farm boundary", selectedImage: "Selected image", verifyingClaim: "Verifying claim…", claimSubmissionError: "Claim submission error", claimVerificationResult: "Claim verification result", claimResultDescription: "Image analysis and review triage for your submitted claim.", farmerClaimedLoss: "Farmer claimed loss", loginRequired: "Please login or register to use this feature.", selectStateDistrict: "Please select both State and District.", analysisFailed: "Analysis failed: {{message}}", completeClaimFields: "Please complete all claim fields and upload a crop image.", deleteClaimConfirm: "Are you sure you want to delete this claim from history?",
  close: "Close", cropDamageDetection: "Crop Damage Detection", loadClaimsFailed: "Failed to load insurance claims.", loginFailed: "Login failed. Please try again.", registrationFailed: "Registration failed. Please try again.", requiredFields: "Please fill in all fields.", profileUpdateFailed: "Failed to update profile.",
  predictionUnavailable: "Prediction unavailable", unavailable: "Unavailable", supportingEvidence: "Visual Heuristic Estimate — Supporting Evidence", supportingEvidenceDescription: "Colour-based image damage estimate and evidence index for the reviewing officer — this is not an AI damage prediction.", humanDecisionRequired: "Human decision required — this heuristic score cannot approve, reject, or calculate a PMFBY payout.", priorityExplanation: "Why this priority was assigned", trainedMlModel: "Trained ML Model", model: "Model", claimRiskScore: "Claim Risk Score", trainedModelTriage: "This triage comes from the trained claim-risk ML model.", humanOfficerDecision: "The system does not automatically approve, reject, or calculate a PMFBY payout — a human officer makes the final decision.", modelNotReady: "Model not ready", awaitingVerifiedClaims: "Awaiting sufficient officer-verified claim records for ML triage.", humanOfficerReview: "The system does not automatically approve, reject, or calculate a PMFBY payout — a human officer reviews this claim.", reviewDecision: "Review Decision", noReviewReason: "No review reason returned.", normalProcess: "Your claim can continue through the normal PMFBY process.", continueToPortal: "Continue to Official PMFBY Portal", additionalVerification: "Additional verification is required before the claim proceeds.", underVerification: "Under Verification", detailedVerification: "Detailed manual verification is required before the claim proceeds.", highPriorityReview: "High-priority manual review required",
  claimsStored: "Claims stored in the backend database", totalClaims: "Total Claims", noMatchingClaims: "No claims match your search or selected status.", crop: "Crop", aiPrediction: "AI Prediction", mlTriage: "ML Triage", action: "Action", demoMl: "Demo ML", ml: "ML", modelPendingReview: "Model not ready — pending review",
  analysisReports: "Analysis Reports", reportsSubtitle: "View and download crop damage assessment reports", assessmentReport: "PMFBY Crop Damage Assessment Report", remoteSensingAnalysis: "AI & Remote Sensing Based Crop Damage Analysis", reportStudyArea: "1. Study Area", analysisPeriod: "2. Analysis Period", damageResults: "3. Crop Damage Analysis Results", totalCropland: "Total Cropland", potentialDamagedArea: "Potential Damaged Area", damagePercentage: "Damage Percentage", satelliteData: "4. Satellite Data", satelliteSource: "Satellite Source", analysisPlatform: "Analysis Platform", assessmentConclusion: "5. Assessment Conclusion", assessmentConclusionText: "The analysis identified approximately {{damagedArea}} hectares of potential crop damage, representing {{damagePercentage}}% of the analyzed cropland area.", disclaimer: "Disclaimer", reportDisclaimer: "Results represent potential vegetation loss based on satellite-derived analysis and should be verified through field assessment before final insurance decisions.", downloadReport: "Download Report", noReport: "No Analysis Report Yet", noReportDescription: "Run the crop damage analysis first to generate a report.", goToStudyArea: "Go to Study Area", ndviDescription: "NDVI-based crop damage assessment using Sentinel-2 satellite imagery", analysisStatus: "Analysis Status", satelliteProcessing: "Satellite data is being processed…", analysisCompleted: "Analysis completed successfully", analysisReady: "Ready to start analysis", processing: "Processing", completed: "Completed", ready: "Ready", method: "Method", ndviChangeDetection: "NDVI Change Detection", analysisComplete: "Analysis Complete", locationTitle: "{{district}} District, {{state}}", pmfbySatelliteAssessment: "PMFBY Crop Damage Assessment using Sentinel-2 Satellite Data", satelliteDerived: "Satellite derived", potentialDamage: "Potential Damage", ndviDetection: "NDVI based detection", estimatedAffectedArea: "Estimated affected area", dataSource: "Data Source", cropDamageMap: "Crop Damage Map", districtDamageAnalysis: "{{district}} crop damage analysis", ndviAnalysis: "NDVI Analysis", generateMap: "Click Analyze {{district}} to generate the crop damage map", healthyVegetation: "Healthy Vegetation", analysisSummary: "Analysis Summary", processingWorkflow: "Current processing workflow", satelliteDataCollection: "Satellite Data Collection", ndviCalculation: "NDVI Calculation", damageDetection: "Damage Detection", refinedAnalysis: "Refined Analysis", sentinelCollected: "Sentinel-2 images collected", vegetationComparison: "Before and after vegetation comparison", vegetationLossIdentified: "Potential vegetation loss identified", croplandMasking: "Cropland masking and noise reduction", finalReport: "Final Report", resultsGenerated: "Results and damage summary generated", resultsSummary: "Results and damage summary", viewReport: "View Report"
};

// Farmer-facing claim fields are deliberately present for every supported
// script, including locales that were previously only translated in the menu.
const claimFieldTranslations = {
  hi: { cropName:"फसल का नाम", claimedLoss:"दावा की गई फसल हानि (%)", farmArea:"खेत का क्षेत्रफल (एकड़)", farmLocation:"खेत का स्थान / गाँव", claimDetails:"किसान के दावे का विवरण", evidenceForHumanReview:"मानवीय समीक्षा के लिए साक्ष्य", evidenceDescription:"ये विवरण खेत-स्तरीय सत्यापन में सहायता करते हैं।", claimEventType:"दावा घटना प्रकार", cropStage:"फसल अवस्था", claimDate:"दावा तिथि", sowingDate:"बुवाई तिथि", selectEvent:"घटना चुनें", selectCropStage:"फसल अवस्था चुनें", exampleCrop:"उदाहरण: अंगूर, सेब, टमाटर", exampleLoss:"उदाहरण: 40", exampleArea:"उदाहरण: 2.5", villagePlaceholder:"गाँव या खेत का स्थान दर्ज करें", uploadImage:"फसल क्षति की छवि अपलोड करें" },
  mr: { cropName:"पिकाचे नाव", claimedLoss:"दावा केलेले पीक नुकसान (%)", farmArea:"शेताचे क्षेत्रफळ (एकर)", farmLocation:"शेताचे ठिकाण / गाव", claimDetails:"शेतकरी दाव्याचा तपशील", evidenceForHumanReview:"मानवी पुनरावलोकनासाठी पुरावे", evidenceDescription:"हे तपशील क्षेत्र-स्तरीय पडताळणीस मदत करतात.", claimEventType:"दावा घटना प्रकार", cropStage:"पीक अवस्था", claimDate:"दावा तारीख", sowingDate:"पेरणी तारीख", selectEvent:"घटना निवडा", selectCropStage:"पीक अवस्था निवडा", exampleCrop:"उदाहरण: द्राक्षे, सफरचंद, टोमॅटो", exampleLoss:"उदाहरण: 40", exampleArea:"उदाहरण: 2.5", villagePlaceholder:"गाव किंवा शेताचे ठिकाण भरा", uploadImage:"पीक नुकसानीचा फोटो अपलोड करा" },
  ta: { cropName:"பயிர் பெயர்", claimedLoss:"கோரப்பட்ட பயிர் இழப்பு (%)", farmArea:"பண்ணை பரப்பளவு (ஏக்கர்)", farmLocation:"பண்ணை இடம் / கிராமம்", claimDetails:"விவசாயியின் கோரிக்கை விவரங்கள்", evidenceForHumanReview:"மனித மதிப்பாய்வுக்கான சான்று", evidenceDescription:"இந்த விவரங்கள் வயல் அளவிலான சரிபார்ப்புக்கு உதவுகின்றன.", claimEventType:"கோரிக்கை நிகழ்வு வகை", cropStage:"பயிர் நிலை", claimDate:"கோரிக்கை தேதி", sowingDate:"விதைப்பு தேதி", selectEvent:"நிகழ்வைத் தேர்ந்தெடுக்கவும்", selectCropStage:"பயிர் நிலையைத் தேர்ந்தெடுக்கவும்", exampleCrop:"உதாரணம்: திராட்சை, ஆப்பிள், தக்காளி", exampleLoss:"உதாரணம்: 40", exampleArea:"உதாரணம்: 2.5", villagePlaceholder:"கிராமம் அல்லது பண்ணை இடத்தை உள்ளிடவும்", uploadImage:"பயிர் சேதப் படத்தைப் பதிவேற்றவும்" },
  te: { cropName:"పంట పేరు", claimedLoss:"క్లెయిమ్ చేసిన పంట నష్టం (%)", farmArea:"పొలం విస్తీర్ణం (ఎకరాలు)", farmLocation:"పొలం స్థానం / గ్రామం", claimDetails:"రైతు క్లెయిమ్ వివరాలు", evidenceForHumanReview:"మానవ సమీక్షకు ఆధారం", evidenceDescription:"ఈ వివరాలు క్షేత్ర-స్థాయి ధృవీకరణకు సహాయపడతాయి.", claimEventType:"క్లెయిమ్ ఘటన రకం", cropStage:"పంట దశ", claimDate:"క్లెయిమ్ తేదీ", sowingDate:"విత్తిన తేదీ", selectEvent:"ఘటనను ఎంచుకోండి", selectCropStage:"పంట దశను ఎంచుకోండి", exampleCrop:"ఉదాహరణ: ద్రాక్ష, ఆపిల్, టమాటా", exampleLoss:"ఉదాహరణ: 40", exampleArea:"ఉదాహరణ: 2.5", villagePlaceholder:"గ్రామం లేదా పొలం స్థానాన్ని నమోదు చేయండి", uploadImage:"పంట నష్టం చిత్రాన్ని అప్‌లోడ్ చేయండి" },
  bn: { cropName:"ফসলের নাম", claimedLoss:"দাবিকৃত ফসলের ক্ষতি (%)", farmArea:"খামারের এলাকা (একর)", farmLocation:"খামারের অবস্থান / গ্রাম", claimDetails:"কৃষকের দাবি বিবরণ", evidenceForHumanReview:"মানব পর্যালোচনার প্রমাণ", claimEventType:"দাবি ঘটনার ধরন", cropStage:"ফসলের পর্যায়", claimDate:"দাবির তারিখ", sowingDate:"বপনের তারিখ", selectEvent:"ঘটনা নির্বাচন করুন", selectCropStage:"ফসলের পর্যায় নির্বাচন করুন", villagePlaceholder:"গ্রাম বা খামারের অবস্থান লিখুন", uploadImage:"ফসল ক্ষতির ছবি আপলোড করুন" },
  gu: { cropName:"પાકનું નામ", claimedLoss:"દાવો કરેલ પાક નુકસાન (%)", farmArea:"ખેતર વિસ્તાર (એકર)", farmLocation:"ખેતરનું સ્થાન / ગામ", claimDetails:"ખેડૂતના દાવાની વિગતો", evidenceForHumanReview:"માનવ સમીક્ષા માટે પુરાવા", claimEventType:"દાવાની ઘટના પ્રકાર", cropStage:"પાકનો તબક્કો", claimDate:"દાવાની તારીખ", sowingDate:"વાવણી તારીખ", selectEvent:"ઘટના પસંદ કરો", selectCropStage:"પાકનો તબક્કો પસંદ કરો", villagePlaceholder:"ગામ અથવા ખેતરનું સ્થાન લખો", uploadImage:"પાક નુકસાનની છબી અપલોડ કરો" },
  kn: { cropName:"ಬೆಳೆಯ ಹೆಸರು", claimedLoss:"ಕೋರಿದ ಬೆಳೆ ನಷ್ಟ (%)", farmArea:"ಹೊಲದ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)", farmLocation:"ಹೊಲದ ಸ್ಥಳ / ಗ್ರಾಮ", claimDetails:"ರೈತರ ಹಕ್ಕು ವಿವರಗಳು", evidenceForHumanReview:"ಮಾನವ ಪರಿಶೀಲನೆಗೆ ಸಾಕ್ಷ್ಯ", claimEventType:"ಹಕ್ಕು ಘಟನೆ ಪ್ರಕಾರ", cropStage:"ಬೆಳೆ ಹಂತ", claimDate:"ಹಕ್ಕು ದಿನಾಂಕ", sowingDate:"ಬಿತ್ತನೆ ದಿನಾಂಕ", selectEvent:"ಘಟನೆ ಆಯ್ಕೆಮಾಡಿ", selectCropStage:"ಬೆಳೆ ಹಂತ ಆಯ್ಕೆಮಾಡಿ", villagePlaceholder:"ಗ್ರಾಮ ಅಥವಾ ಹೊಲದ ಸ್ಥಳ ನಮೂದಿಸಿ", uploadImage:"ಬೆಳೆ ಹಾನಿಯ ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ" },
  ml: { cropName:"വിളയുടെ പേര്", claimedLoss:"അവകാശപ്പെട്ട വിളനഷ്ടം (%)", farmArea:"കൃഷിയിട വിസ്തീർണം (ഏക്കർ)", farmLocation:"കൃഷിയിട സ്ഥലം / ഗ്രാമം", claimDetails:"കർഷകന്റെ ക്ലെയിം വിവരങ്ങൾ", evidenceForHumanReview:"മനുഷ്യ പരിശോധനയ്ക്കുള്ള തെളിവ്", claimEventType:"ക്ലെയിം സംഭവ തരം", cropStage:"വിള ഘട്ടം", claimDate:"ക്ലെയിം തീയതി", sowingDate:"വിത്തിടൽ തീയതി", selectEvent:"സംഭവം തിരഞ്ഞെടുക്കുക", selectCropStage:"വിള ഘട്ടം തിരഞ്ഞെടുക്കുക", villagePlaceholder:"ഗ്രാമം അല്ലെങ്കിൽ കൃഷിയിടം നൽകുക", uploadImage:"വിളനാശ ചിത്രം അപ്‌ലോഡ് ചെയ്യുക" },
  pa: { cropName:"ਫਸਲ ਦਾ ਨਾਮ", claimedLoss:"ਦਾਅਵਾ ਕੀਤਾ ਫਸਲ ਨੁਕਸਾਨ (%)", farmArea:"ਖੇਤ ਦਾ ਖੇਤਰਫਲ (ਏਕੜ)", farmLocation:"ਖੇਤ ਦਾ ਸਥਾਨ / ਪਿੰਡ", claimDetails:"ਕਿਸਾਨ ਦੇ ਦਾਅਵੇ ਦੇ ਵੇਰਵੇ", evidenceForHumanReview:"ਮਨੁੱਖੀ ਸਮੀਖਿਆ ਲਈ ਸਬੂਤ", claimEventType:"ਦਾਅਵੇ ਦੀ ਘਟਨਾ ਕਿਸਮ", cropStage:"ਫਸਲ ਪੜਾਅ", claimDate:"ਦਾਅਵੇ ਦੀ ਤਾਰੀਖ", sowingDate:"ਬਿਜਾਈ ਦੀ ਤਾਰੀਖ", selectEvent:"ਘਟਨਾ ਚੁਣੋ", selectCropStage:"ਫਸਲ ਪੜਾਅ ਚੁਣੋ", villagePlaceholder:"ਪਿੰਡ ਜਾਂ ਖੇਤ ਦਾ ਸਥਾਨ ਦਾਖਲ ਕਰੋ", uploadImage:"ਫਸਲ ਨੁਕਸਾਨ ਚਿੱਤਰ ਅੱਪਲੋਡ ਕਰੋ" },
  as: { cropName:"শস্যৰ নাম", claimedLoss:"দাবী কৰা শস্য ক্ষতি (%)", farmArea:"খেতিৰ মাটি (একৰ)", farmLocation:"খেতিৰ স্থান / গাঁও", claimDetails:"কৃষকৰ দাবীৰ বিৱৰণ", evidenceForHumanReview:"মানৱ পৰ্যালোচনাৰ প্ৰমাণ", claimEventType:"দাবী ঘটনাৰ ধৰণ", cropStage:"শস্যৰ পৰ্যায়", claimDate:"দাবীৰ তাৰিখ", sowingDate:"বীজ সিঁচা তাৰিখ", selectEvent:"ঘটনা বাছক", selectCropStage:"শস্যৰ পৰ্যায় বাছক", villagePlaceholder:"গাঁও বা খেতিৰ স্থান লিখক", uploadImage:"শস্য ক্ষতিৰ ছবি আপল'ড কৰক" },
  or: { cropName:"ଫସଲର ନାମ", claimedLoss:"ଦାବି କରାଯାଇଥିବା ଫସଲ କ୍ଷତି (%)", farmArea:"ଚାଷ ଜମି କ୍ଷେତ୍ରଫଳ (ଏକର)", farmLocation:"ଚାଷ ଜମି ସ୍ଥାନ / ଗାଁ", claimDetails:"କୃଷକଙ୍କ ଦାବି ବିବରଣୀ", evidenceForHumanReview:"ମାନବ ସମୀକ୍ଷା ପାଇଁ ପ୍ରମାଣ", claimEventType:"ଦାବି ଘଟଣା ପ୍ରକାର", cropStage:"ଫସଲ ପର୍ଯ୍ୟାୟ", claimDate:"ଦାବି ତାରିଖ", sowingDate:"ବୁଣିବା ତାରିଖ", selectEvent:"ଘଟଣା ବାଛନ୍ତୁ", selectCropStage:"ଫସଲ ପର୍ଯ୍ୟାୟ ବାଛନ୍ତୁ", villagePlaceholder:"ଗାଁ କିମ୍ବା ଚାଷ ଜମି ସ୍ଥାନ ଲେଖନ୍ତୁ", uploadImage:"ଫସଲ କ୍ଷତି ଛବି ଅପଲୋଡ କରନ୍ତୁ" }
};

// Satellite dashboard copy is separate from form copy so technical terms such
// as Sentinel-2, NDVI, and Google Earth Engine remain untouched while every
// surrounding farmer-facing label changes with the selected language.
const dashboardTranslations = {
  mr: { satelliteAnalysis:"संभाव्य पीक नुकसान ओळखण्यासाठी उपग्रह-आधारित विश्लेषण", locationTitle:"{{district}} जिल्हा, {{state}}", pmfbySatelliteAssessment:"Sentinel-2 उपग्रह डेटाचा वापर करून PMFBY पीक नुकसान मूल्यांकन", totalCropland:"एकूण पीक क्षेत्र", potentialDamage:"संभाव्य नुकसान", damagePercentage:"नुकसान टक्केवारी", dataSource:"डेटा स्रोत", satelliteDerived:"उपग्रहावरून प्राप्त", ndviDetection:"NDVI आधारित शोध", ndviChangeDetection:"NDVI बदल शोध", estimatedAffectedArea:"अंदाजे बाधित क्षेत्र", cropDamageMap:"पीक नुकसान नकाशा", ndviAnalysis:"NDVI विश्लेषण", analysisSummary:"विश्लेषण सारांश", processingWorkflow:"सध्याचा प्रक्रिया प्रवाह", satelliteDataCollection:"उपग्रह डेटा संकलन", sentinelCollected:"Sentinel-2 प्रतिमा संकलित केल्या", ndviCalculation:"NDVI गणना", vegetationComparison:"घटनेपूर्वी आणि नंतरची वनस्पती तुलना", damageDetection:"नुकसान शोध", vegetationLossIdentified:"संभाव्य वनस्पती हानी ओळखली", refinedAnalysis:"परिष्कृत विश्लेषण", croplandMasking:"पीक क्षेत्र मास्किंग आणि आवाज कमी करणे", generateMap:"पीक नुकसान नकाशा तयार करण्यासाठी {{district}} चे विश्लेषण करा", healthyVegetation:"निरोगी वनस्पती", finalReport:"अंतिम अहवाल", resultsGenerated:"निकाल आणि नुकसान सारांश तयार झाला", resultsSummary:"निकाल आणि नुकसान सारांश", viewReport:"अहवाल पहा", analysisComplete:"विश्लेषण पूर्ण", analysisReady:"विश्लेषणासाठी तयार" },
  hi: { satelliteAnalysis:"संभावित फसल क्षति पहचानने के लिए उपग्रह-आधारित विश्लेषण", locationTitle:"{{district}} जिला, {{state}}", totalCropland:"कुल फसल क्षेत्र", potentialDamage:"संभावित क्षति", damagePercentage:"क्षति प्रतिशत", dataSource:"डेटा स्रोत", cropDamageMap:"फसल क्षति मानचित्र", analysisSummary:"विश्लेषण सारांश", satelliteDataCollection:"उपग्रह डेटा संग्रह", ndviCalculation:"NDVI गणना", damageDetection:"क्षति पहचान", refinedAnalysis:"परिष्कृत विश्लेषण", healthyVegetation:"स्वस्थ वनस्पति", finalReport:"अंतिम रिपोर्ट", viewReport:"रिपोर्ट देखें" },
  ta: { satelliteAnalysis:"சாத்தியமான பயிர் சேதத்தை அடையாளம் காண செயற்கைக்கோள் அடிப்படையிலான பகுப்பாய்வு", totalCropland:"மொத்த பயிர் நிலம்", potentialDamage:"சாத்தியமான சேதம்", damagePercentage:"சேத சதவீதம்", dataSource:"தரவு மூலம்", cropDamageMap:"பயிர் சேத வரைபடம்", analysisSummary:"பகுப்பாய்வு சுருக்கம்", satelliteDataCollection:"செயற்கைக்கோள் தரவு சேகரிப்பு", ndviCalculation:"NDVI கணக்கீடு", damageDetection:"சேதம் கண்டறிதல்", finalReport:"இறுதி அறிக்கை", viewReport:"அறிக்கையைப் பார்க்கவும்" },
  te: { satelliteAnalysis:"సంభావ్య పంట నష్టాన్ని గుర్తించడానికి ఉపగ్రహ ఆధారిత విశ్లేషణ", totalCropland:"మొత్తం పంట భూమి", potentialDamage:"సంభావ్య నష్టం", damagePercentage:"నష్టం శాతం", dataSource:"డేటా మూలం", cropDamageMap:"పంట నష్టం పటం", analysisSummary:"విశ్లేషణ సారాంశం", satelliteDataCollection:"ఉపగ్రహ డేటా సేకరణ", ndviCalculation:"NDVI గణన", damageDetection:"నష్టం గుర్తింపు", finalReport:"చివరి నివేదిక", viewReport:"నివేదిక చూడండి" }
};

// The initial Marathi file covered the menu and claim basics but omitted the
// page-specific fallback keys below. Keep these overrides together so every
// visible label in the existing single-page UI resolves before English.
const marathiOverrides = {
  cropDamageDashboard: "पीक नुकसान शोध डॅशबोर्ड",
  analyze: "{{district}} चे विश्लेषण करा",
  selectStudy: "अभ्यास क्षेत्र निवडा",
  studySubtitle: "पीक नुकसान विश्लेषणासाठी स्थान आणि कालावधी निवडा",
  selectState: "राज्य निवडा", selectDistrict: "जिल्हा निवडा",
  beforeEvent: "घटनेपूर्वीचा कालावधी", afterEvent: "घटनेनंतरचा कालावधी",
  startDate: "सुरुवातीची तारीख", endDate: "समाप्तीची तारीख",
  analysisReports: "विश्लेषण अहवाल", reportsSubtitle: "पीक नुकसान मूल्यांकन अहवाल पहा आणि डाउनलोड करा",
  noReport: "अजून विश्लेषण अहवाल नाही", noReportDescription: "अहवाल तयार करण्यासाठी प्रथम पीक नुकसान विश्लेषण चालवा.",
  goToStudyArea: "अभ्यास क्षेत्राकडे जा", assessmentReport: "PMFBY पीक नुकसान मूल्यांकन अहवाल",
  remoteSensingAnalysis: "AI आणि रिमोट सेन्सिंग आधारित पीक नुकसान विश्लेषण",
  analysisStatus: "विश्लेषण स्थिती", ready: "तयार", processing: "प्रक्रिया सुरू आहे", completed: "पूर्ण झाले",
  ndviDescription: "Sentinel-2 उपग्रह प्रतिमांचा वापर करून NDVI-आधारित पीक नुकसान मूल्यांकन",
  method: "पद्धत", ndviChangeDetection: "NDVI बदल शोध",
  searchClaims: "पीक, स्थान, जिल्हा, राज्य किंवा रोगाने शोधा…", allStatuses: "सर्व स्थिती",
  totalClaims: "एकूण दावे", claimsStored: "बॅकएंड डेटाबेसमध्ये संग्रहित दावे",
  crop: "पीक", aiPrediction: "AI अंदाज", mlTriage: "ML वर्गीकरण", action: "कृती",
  status: "स्थिती", delete: "हटवा", noMatchingClaims: "तुमच्या शोधाशी किंवा निवडलेल्या स्थितीशी कोणताही दावा जुळत नाही.",
  claimHistory: "विमा दावा इतिहास", normalReview: "सामान्य पुनरावलोकन", mediumReview: "मध्यम पुनरावलोकन", highReview: "उच्च पुनरावलोकन",
  potentialDamagedArea: "संभाव्य नुकसानग्रस्त क्षेत्र", satelliteData: "उपग्रह डेटा", satelliteSource: "उपग्रह स्रोत", analysisPlatform: "विश्लेषण मंच",
  reportStudyArea: "1. अभ्यास क्षेत्र", analysisPeriod: "2. विश्लेषण कालावधी", damageResults: "3. पीक नुकसान विश्लेषण निकाल",
  assessmentConclusion: "5. मूल्यांकन निष्कर्ष", disclaimer: "अस्वीकरण", downloadReport: "अहवाल डाउनलोड करा",
  loginRequired: "हे वैशिष्ट्य वापरण्यासाठी लॉगिन किंवा नोंदणी करा.", loading: "लोड होत आहे…",
  enterFullName: "तुमचे पूर्ण नाव भरा", phonePlaceholder: "10 अंकी मोबाईल क्रमांक", usernamePlaceholder: "वापरकर्तानाव निवडा", passwordPlaceholder: "किमान 6 अक्षरे", confirmPasswordPlaceholder: "पासवर्ड पुन्हा भरा",
  loginSubtitle: "PMFBY पीक नुकसान शोधासाठी लॉगिन करा", registerSubtitle: "पीक नुकसान विश्लेषण सुरू करण्यासाठी नोंदणी करा"
};

export function translate(language, key, values = {}) {
  const places = {
    mr: { Nagpur: "नागपूर", Maharashtra: "महाराष्ट्र" },
    hi: { Nagpur: "नागपुर", Maharashtra: "महाराष्ट्र" },
    ta: { Nagpur: "நாக்பூர்", Maharashtra: "மகாராஷ்டிரா" },
    te: { Nagpur: "నాగ్‌పూర్", Maharashtra: "మహారాష్ట్ర" },
    bn: { Nagpur: "নাগপুর", Maharashtra: "মহারাষ্ট্র" },
    gu: { Nagpur: "નાગપુર", Maharashtra: "મહારાષ્ટ્ર" },
    kn: { Nagpur: "ನಾಗ್ಪುರ", Maharashtra: "ಮಹಾರಾಷ್ಟ್ರ" },
    ml: { Nagpur: "നാഗ്പുർ", Maharashtra: "മഹാരാഷ്ട്ര" },
    pa: { Nagpur: "ਨਾਗਪੁਰ", Maharashtra: "ਮਹਾਰਾਸ਼ਟਰ" },
    as: { Nagpur: "নাগপুৰ", Maharashtra: "মহাৰাষ্ট্ৰ" },
    or: { Nagpur: "ନାଗପୁର", Maharashtra: "ମହାରାଷ୍ଟ୍ର" },
  };
  if (key.startsWith("place.")) return places[language]?.[key.slice(6)] ?? key.slice(6);
  let value = (language === "mr" ? marathiOverrides[key] : undefined) ?? catalogs[language]?.[key] ?? claimFieldTranslations[language]?.[key] ?? dashboardTranslations[language]?.[key] ?? en[key] ?? defaults[key] ?? key;
  Object.entries(values).forEach(([name, replacement]) => { value = value.replaceAll(`{{${name}}}`, replacement); });
  return value;
}
